services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    image: keep-cooking-api:latest
    container_name: api
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 8000
      # FLASK_STAGE (dev or prod)
      FLASK_STAGE: dev
      FRONTEND_URL: "http://localhost:3000"
      # Enable or disable SSL
      SSL_ENABLE: "false"
      # Internal path to the SSL key (not host path)
      SSL_CERT_PATH: /certs/fullchain.pem
      SSL_KEY_PATH: /certs/privkey.pem
      API_BASE: http://localhost:8000/api
    ports:
      - "8000:8000"
    volumes:
      # volume mount the database so it doesn't reset when container restarts
      - ./src/data:/app/src/data
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        LOCAL_FRONTEND_REPO: https://github.com/Keep-Cooking/frontend
        API_BASE: "http://localhost:8000/api"
        FRONTEND_PORT: 3000
    image: keep-cooking-frontend:latest
    container_name: frontend
    ports:
      # change to expose a port other than 3000
      - "3000:3000"
    restart: unless-stopped
